name: Type Checking with stubtest

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  stubtest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install boost cmake

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy typing-extensions wheel setuptools

    - name: Build SVF-Python
      run: |
        # Build and install the package
        bash build.sh
        python -m pip install dist/pysvf-*.whl

    - name: Run stubtest
      run: |
        # Create __pycache__ directory if it doesn't exist to avoid issues
        mkdir -p pysvf/__pycache__
        
        # Run stubtest with allowlist
        python -m mypy.stubtest pysvf --allowlist stubtest_allowlist.txt
        
    - name: Upload stub errors if failed
      if: failure()
      run: |
        # Save stubtest errors to file
        python -m mypy.stubtest pysvf > stubtest_errors.log
        
    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: stubtest-errors-${{ matrix.os }}-py${{ matrix.python-version }}
        path: stubtest_errors.log