name: Run Notebooks in Tutorials

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  execute-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Jupyter and register kernel
        run: |
          pip install notebook nbconvert nbclient ipykernel
          python -m ipykernel install --user --name python3
          pip install install -i https://test.pypi.org/simple/ pysvf

      - name: Run all notebooks under tutorials/
        run: |
          cd tutorials
          for nb in $(find . -name "*.ipynb"); do
            echo "Executing $nb..."
            jupyter nbconvert --to notebook --execute "$nb" --stdout > /dev/null
          done
