name: Run Notebooks in Tutorials

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  execute-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ python3-dev python3-pip nodejs

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install notebook nbconvert nbclient ipykernel build pybind11

      - name: Register Jupyter kernel
        run: |
          python -m ipykernel install --user --name python3

      - name: Install svf-lib and set environment variables
        run: |
          npm install svf-lib
          echo "SVF_DIR=$PWD/node_modules/svf-lib/SVF-linux-x86_64" >> $GITHUB_ENV
          echo "LLVM_DIR=$PWD/node_modules/llvm-16.0.0.obj" >> $GITHUB_ENV
          echo "Z3_DIR=$PWD/node_modules/z3.obj" >> $GITHUB_ENV

      - name: Build & install pysvf locally
        run: |
          git clone https://github.com/SVF-tools/SVF-Python.git
          cd SVF-Python
          rm -rf build dist pysvf.egg-info
          export PYBIND11_DIR=$(python3 -m pybind11 --cmakedir)
          export CMAKE_BUILD_TYPE=Release
          mkdir build && cd build
          cmake -DCMAKE_PREFIX_PATH=$PYBIND11_DIR -DSVF_DIR=$SVF_DIR -DLLVM_DIR=$LLVM_DIR -DZ3_DIR=$Z3_DIR .. 
          make -j$(nproc)
          cd ..
          python -m build
          pip install dist/*.whl

      - name: Run all notebooks in tutorials/
        run: |
          cd tutorials
          for nb in $(find . -name "*.ipynb"); do
            echo "Executing $nb..."
            jupyter nbconvert --to notebook --execute "$nb" --stdout > /dev/null
          done
