name: svf-python-build

on:
  push:
    branches:
      - main  # only build on main branch

env:
  SVF_CTIR: 1
  SVF_Z3: 1
  SVF_DIR: $GITHUB_WORKSPACE/SVF
  LLVM_DIR: $GITHUB_WORKSPACE/SVF/llvm-16.0.0.obj
  Z3_DIR: $GITHUB_WORKSPACE/SVF/z3.obj

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # macOS Xcode
      - name: mac-setup
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3.0'

      - name: mac-setup-workaround
        if: runner.os == 'macOS'
        run: |
          ln -sfn /Applications/Xcode_15.3.0.app /Applications/Xcode.app

      # install linux dependencies
      - name: ubuntu-setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y \
              cmake gcc g++ nodejs doxygen graphviz lcov libncurses5-dev libtinfo6 libzstd-dev \
              python3 python3-pip python3-venv

      # calculate version
      - name: Set VERSION
        id: set_version
        run: |
          VERSION="0.0.0-dev$(expr ${{ github.run_id }} % 1000000)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Clone and Build SVF
        run: |
          git clone https://github.com/SVF-tools/SVF.git
          cd SVF
          bash build.sh shared  
          echo "SVF_DIR=$GITHUB_WORKSPACE/SVF" >> $GITHUB_ENV
          echo "LLVM_DIR=$GITHUB_WORKSPACE/SVF/llvm-16.0.0.obj" >> $GITHUB_ENV
          echo "Z3_DIR=$GITHUB_WORKSPACE/SVF/z3.obj" >> $GITHUB_ENV
          ls -lh $GITHUB_WORKSPACE/SVF/Release-build/lib

        # set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine pybind11

      # clone & build SVF-Python
      - name: Clone and Build SVF-Python
        run: |
          git clone https://github.com/SVF-tools/SVF-Python.git
          cd SVF-Python
          rm -rf build dist pysvf.egg-info  
          export PYBIND11_DIR=$(python3 -m pybind11 --cmakedir)
          export CMAKE_BUILD_TYPE=Release
          SVF_DIR=${SVF_DIR} LLVM_DIR=${LLVM_DIR} Z3_DIR=${Z3_DIR} PYBIND11_DIR=${PYBIND11_DIR} python3 setup.py bdist_wheel
          ls -lh dist/

      # upload Python wheels
      - name: Upload Python wheels
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ env.VERSION }}-${{ runner.os }}
          path: SVF-Python/dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # allow to write to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set VERSION from build job
        run: |
          echo "VERSION=${{ needs.build.outputs.version }}" >> $GITHUB_ENV

      # download linux version
      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          name: python-wheels-${{ env.VERSION }}-Linux
          path: dist/

      # download mac version
      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: python-wheels-${{ env.VERSION }}-macOS
          path: dist/

      # double check files exist
      - name: Verify wheel files
        run: |
          ls -lh dist/
          if [ -z "$(ls -A dist/)" ]; then
            echo "Error: No wheel files found in dist/!"
            exit 1
          fi

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload --repository testpypi dist/*
